Repository testground/testground, pull requests merged in 2019-12, with the labels that each got.

#183 initial daemon implementation
  README.md
  cmd/all.go
  cmd/build.go
  cmd/daemon.go
  cmd/describe.go
  cmd/list.go
  cmd/run.go
  docs/PLAN_SPEC.md
  docs/USAGE.md
  env-example.toml
  go.mod
  go.sum
  pkg/api/builder.go
  pkg/api/common.go
  pkg/api/definitions.go
  pkg/api/env.go
  pkg/api/runner.go
  pkg/aws/ecr.go
  pkg/build/golang/docker.go
  pkg/build/golang/exec.go
  pkg/config/config.go
  pkg/daemon/client/client.go
  pkg/daemon/client/types.go
  pkg/daemon/doc.go
  pkg/docker/container.go
  pkg/docker/network.go
  pkg/engine/discovery.go
  pkg/engine/engine.go
  pkg/inproc/inproc.go
  pkg/logging/log.go
  pkg/runner/cluster_nomad.go
  pkg/runner/cluster_swarm.go
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
  pkg/server/build.go
  pkg/server/describe.go
  pkg/server/errf.go
  pkg/server/list.go
  pkg/server/run.go
  pkg/server/server.go
  pkg/tgwriter/tgwriter.go
  plans/dht/go.mod
Labels: P1 - High

#58 feat: first tests of Chew Large Datasets
  go.sum
  manifests/chew-large-datasets.toml
  plans/chew-large-datasets/README.md
  plans/chew-large-datasets/go.mod
  plans/chew-large-datasets/main.go
  plans/chew-large-datasets/test/ipfs_add_defaults.go
  plans/chew-large-datasets/test/ipfs_add_dir_sharding.go
  plans/chew-large-datasets/test/ipfs_add_trickle_dag.go
  plans/chew-large-datasets/test/ipfs_file_store.go
  plans/chew-large-datasets/test/ipfs_mfs.go
  plans/chew-large-datasets/test/ipfs_mfs_dir_sharding.go
  plans/chew-large-datasets/test/ipfs_url_store.go
  plans/chew-large-datasets/utils/create-ipfs-daemon.go
  plans/chew-large-datasets/utils/create-ipfs-instance.go
  plans/chew-large-datasets/utils/create-random-file.go
  plans/chew-large-datasets/utils/for-each-case.go
  plans/chew-large-datasets/utils/unixfs.go
Labels: P2 - Medium

#223 feat: add go-ipfs daemon support on large dataset plan
  plans/chew-large-datasets/README.md
  plans/chew-large-datasets/go.mod
  plans/chew-large-datasets/main.go
  plans/chew-large-datasets/test/ipfs_add_defaults.go
  plans/chew-large-datasets/test/ipfs_add_dir_sharding.go
  plans/chew-large-datasets/test/ipfs_add_trickle_dag.go
  plans/chew-large-datasets/test/ipfs_file_store.go
  plans/chew-large-datasets/test/ipfs_mfs.go
  plans/chew-large-datasets/test/ipfs_mfs_dir_sharding.go
  plans/chew-large-datasets/test/ipfs_url_store.go
  plans/chew-large-datasets/utils/create-ipfs-daemon.go
  plans/chew-large-datasets/utils/create-ipfs-instance.go
  plans/chew-large-datasets/utils/create-random-file.go
  plans/chew-large-datasets/utils/for-each-case.go
  plans/chew-large-datasets/utils/testcase.go
  plans/chew-large-datasets/utils/testconfig.go
Labels: P2 - Medium

#181 Improve test output. No more false positives on CI
  pkg/runner/console.go
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
Labels: blocked

#179 dht test plan: refactor + ton of fixes
  .travis.yml
  cmd/build.go
  cmd/describe.go
  cmd/list.go
  cmd/run.go
  manifests/dht.toml
  pkg/daemon/client/client.go
  pkg/runner/console.go
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
  pkg/server/build.go
  pkg/server/describe.go
  pkg/server/errf.go
  pkg/server/list.go
  pkg/server/run.go
  pkg/server/server_test.go
  pkg/tgwriter/tgwriter.go
  plans/dht/go.mod
  plans/dht/test/common.go
  plans/dht/test/create-dht-node.go
  plans/dht/test/find_peers.go
  plans/dht/test/find_providers.go
  plans/dht/test/provide-stress.go
  plans/dht/test/provide_stress.go
  plans/dht/test/set-up.go
  plans/dht/test/store_get_value.go
  plans/dht/test/tear-down.go
  sdk/sync/watch.go
  sdk/sync/write.go
Labels: P1 - High
