Repository testground/testground, pull requests merged in 2020-06, with the labels that each got.

#1048 upgrade sdk-go to v0.2.2
  plans/benchmarks/go.mod
  plans/benchmarks/go.sum
  plans/dockercustomize/go.mod
  plans/dockercustomize/go.sum
  plans/example/go.mod
  plans/example/go.sum
  plans/network/go.mod
  plans/network/go.sum
  plans/placebo/go.mod
  plans/placebo/go.sum
  plans/splitbrain/go.mod
  plans/splitbrain/go.sum
Labels: kind/chore, status/awaiting-review

#1057 sidecar: start http server by default
  .circleci/sidecar.yaml
  Makefile
  env-example.toml
  env-kind.toml
  integration_tests/header.sh
  pkg/cmd/sidecar.go
  pkg/runner/cluster_k8s.go
  pkg/runner/local_docker.go
Labels: area/sidecar, kind/enhancement, status/approved-waiting

#1053 build job for macOS
  .circleci/config.yml
Labels: kind/problem, status/awaiting-review

#1051 persistent priority task queue
  go.mod
  go.sum
  pkg/engine/engine.go
  pkg/task/queue.go
  pkg/task/queue_test.go
  pkg/task/storage.go
  pkg/task/storage_test.go
  pkg/task/task.go
  pkg/task/task_test.go
Labels: TaaS, kind/feature, status/changes-requested

#877 storm testplan
  plans/benchmarks/compositions/storm.toml
  plans/benchmarks/go.mod
  plans/benchmarks/grafana-dashboard/storm.json
  plans/benchmarks/main.go
  plans/benchmarks/manifest.toml
  plans/benchmarks/storm.go
Labels: P1, area/testing, kind/test, status/awaiting-review

#1067 change zip to gzip for all runners ; revert run/build ids to length 12
  integration_tests/01_k8s_kind_placebo_ok.sh
  integration_tests/03_exec_go_placebo_ok.sh
  integration_tests/04_docker_placebo_ok.sh
  integration_tests/06_docker_network_ping-pong.sh
  pkg/engine/engine.go
  pkg/runner/common.go
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
Labels: area/runners, kind/bug, status/approved-waiting

#1071 make sidecar tests run everywhere.
  pkg/sidecar/docker_reactor.go
  pkg/sidecar/instance.go
  pkg/sidecar/k8s_network.go
  pkg/sidecar/mock.go
  pkg/sidecar/sidecar_handler.go
  pkg/sidecar/sidecar_linux.go
Labels: area/sidecar, kind/feature, status/approved-waiting

#1072 cli: fix misleading default value.
  pkg/cmd/run.go
Labels: area/ux-cli, kind/problem, status/approved-waiting

#1074 cluster_k8s: fix healthcheck deadlock
  pkg/runner/cluster_k8s.go
Labels: kind/bug, status/awaiting-review

#1075 increase build timeout
  pkg/build/docker_generic.go
  pkg/build/docker_go.go
Labels: kind/chore, status/awaiting-review

#1081 configurable build base image for docker:go
  pkg/build/docker_go.go
Labels: status/awaiting-review

#1085 add the ability to ship extra local sources in builds.
  pkg/api/builder.go
  pkg/api/engine.go
  pkg/api/manifest.go
  pkg/build/docker_generic.go
  pkg/build/docker_go.go
  pkg/build/exec_go.go
  pkg/build/selector_test.go
  pkg/client/client.go
  pkg/cmd/build.go
  pkg/daemon/build.go
  pkg/engine/engine.go
Labels: area/builders, hint/needs-docs
