Repository testground/testground, pull requests merged in 2020-04, with the labels that each got.

#777 benchmarks testplan: split iterations params
  manifests/benchmarks.toml
  plans/benchmarks/benchmarks.go
Labels: status/waiting

#787 restart containers
  pkg/runner/local_docker.go
Labels: Status/Approved-Waiting

#796 setting sysctl on the k8s hosts
  infra/k8s/cluster.yaml
Labels: status/waiting

#785 ulimits kubernetes using kops
  infra/k8s/cluster.yaml
  infra/k8s/install.sh
Labels: Status/Approved-Waiting, area/infra, area/runners, effort/minutes

#775 speed up install.sh
  infra/k8s/install.sh
Labels: Status/Approved-Waiting

#798 update linux networking stack configuration.
  infra/k8s/cluster.yaml
  infra/k8s/testground-infra/values.yaml
Labels: Status/Approved-Waiting, area/infra, area/testing, kind/enhancement, kind/spike

#734 DRY out the healthcheck api; use containers for local:exec dependencies; wire context to healthchecks
  .travis.yml
  pkg/api/healthchecker.go
  pkg/build/golang/docker.go
  pkg/docker/container.go
  pkg/docker/image.go
  pkg/docker/network.go
  pkg/docker/volume.go
  pkg/engine/engine.go
  pkg/healthcheck/checkers.go
  pkg/healthcheck/fixers.go
  pkg/healthcheck/helper.go
  pkg/runner/cluster_k8s.go
  pkg/runner/local_common.go
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
Labels: Status/Approved-Waiting

#803 allow ecr access from k8s
  infra/k8s/cluster.yaml
Labels: kind/improvement, status/waiting

#822 redis qos guaranteed - set both requests and limits
  infra/k8s/testground-infra/values.yaml
Labels: status/waiting

#784 ulimits local:docker
  env-example.toml
  pkg/conv/conversions.go
  pkg/runner/local_docker.go
Labels: area/runners, effort/minutes, status/waiting

#722 Enhance the DHT test
  Makefile
  compositions/all-balsam-k8s.toml
  compositions/all-both-k8s.toml
  compositions/all-cypress-k8s.toml
  compositions/barrier.toml
  compositions/bootstrap-network-cypress-k8s.toml
  compositions/find-provs-balsam-k8s.toml
  compositions/find-provs-both-k8s.toml
  compositions/find-provs-both-local.toml
  compositions/find-provs-cypress-k8s.toml
  compositions/find-provs-k8s.toml
  compositions/find-provs.toml
  compositions/gcp-balsam-k8s.toml
  compositions/gcp-cypress-k8s.toml
  manifests/dht.toml
  pkg/runner/cluster_k8s.go
  plans/dht/go.mod
  plans/dht/graphs.ps1
  plans/dht/libp2p/addrs.go
  plans/dht/main.go
  plans/dht/results.ps1
  plans/dht/scripts/graphs.ps1
  plans/dht/scripts/prov-results.ps1
  plans/dht/scripts/results.ps1
  plans/dht/test/all.go
  plans/dht/test/barrier.go
  plans/dht/test/boostrap_network.go
  plans/dht/test/common.go
  plans/dht/test/dht_shim_balsam.go
  plans/dht/test/dht_shim_cypress.go
  plans/dht/test/find_peers.go
  plans/dht/test/find_providers.go
  plans/dht/test/get_closest_peers.go
  plans/dht/test/store_get_value.go
  plans/dht/test/sync.go
  plans/dht/test/tracers.go
  plans/dht/utils/identifiers.go
  plans/dht/utils/runinfo.go
  plans/dht/utils/staging.go
  sdk/runtime/runenv.go
  sdk/runtime/runner.go
Labels: status/in-progress

#799 fix: close response and read full
  sdk/runtime/runner.go
Labels: kind/bug

#844 rm TEST_CASE_SEQ as a selector; replace with test case name.
  docs/USAGE.md
  manifests/bitswap-tuning.toml
  manifests/dht.toml
  manifests/placebo.toml
  pkg/api/definitions.go
  pkg/api/runner.go
  pkg/engine/engine.go
  pkg/runner/cluster_k8s.go
  pkg/runner/cluster_swarm.go
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
  plans/bitswap-tuning/main.go
  plans/dht/main.go
  plans/network/main.go
  plans/placebo/main.go
  sdk/runtime/output.go
  sdk/runtime/runenv.go
  sdk/runtime/runenv_test.go
  sdk/runtime/runner.go
  sdk/sync/redis_test.go
Labels: status/waiting

#816 k8s healthcheck checker api
  pkg/healthcheck/checkers.go
  pkg/healthcheck/fixers.go
  pkg/runner/cluster_k8s.go
Labels: status/waiting for review

#829 pod resources per composition group
  pkg/api/composition.go
  pkg/api/runner.go
  pkg/engine/engine.go
  pkg/runner/cluster_k8s.go
  pkg/runner/common.go
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
Labels: Status/Approved-Waiting

#841 rewrite the sync service; migrate all usages.
  compositions/all-cypress-k8s.toml
  go.sum
  pkg/sidecar/docker_reactor.go
  pkg/sidecar/instance.go
  pkg/sidecar/k8s_reactor.go
  pkg/sidecar/sidecar_linux.go
  plans/benchmarks/benchmarks.go
  plans/benchmarks/go.mod
  plans/bitswap-tuning/test/fuzz.go
  plans/bitswap-tuning/test/transfer.go
  plans/bitswap-tuning/utils/net.go
  plans/bitswap-tuning/utils/state.go
  plans/dht/libp2p/addrs.go
  plans/dht/test/common.go
  plans/dht/test/sync.go
  plans/dht/utils/identifiers.go
  plans/dht/utils/runinfo.go
  plans/dht/utils/staging.go
  plans/example/sync.go
  plans/network/main.go
  sdk/sync/barrier_test.go
  sdk/sync/client.go
  sdk/sync/client_consumer.go
  sdk/sync/client_gc.go
  sdk/sync/client_state.go
  sdk/sync/client_sugar.go
  sdk/sync/client_topic.go
  sdk/sync/client_workers.go
  sdk/sync/common.go
  sdk/sync/common_test.go
  sdk/sync/context.go
  sdk/sync/doc.go
  sdk/sync/dump.rdb
  sdk/sync/gc_test.go
  sdk/sync/generic_client_test.go
  sdk/sync/go.mod
  sdk/sync/go.sum
  sdk/sync/helper.go
  sdk/sync/network.go
  sdk/sync/redis_bench_test.go
  sdk/sync/redis_test.go
  sdk/sync/subscription.go
  sdk/sync/topic_test.go
  sdk/sync/types.go
  sdk/sync/watch.go
  sdk/sync/write.go
Labels: area/sdk-sync, impact/quality, kind/enhancement, status/waiting for review

#863 bugfix: panic on sync service closure.
  sdk/sync/client_workers.go
Labels: kind/bug

#802 speed up the Travis build a bit; improve Makefile
  .travis.yml
  Makefile
Labels: kind/improvement, status/waiting for review

#859 remove k8s scripts
  infra/k8s/README.md
  infra/k8s/cluster.yaml
  infra/k8s/delete.sh
  infra/k8s/efs-terraform/backend.tf
  infra/k8s/efs-terraform/main.tf
  infra/k8s/efs-terraform/outputs.tf
  infra/k8s/efs-terraform/variables.tf
  infra/k8s/efs/manifest.yaml.spec
  infra/k8s/efs/rbac.yaml
  infra/k8s/install.sh
  infra/k8s/kops-weave/dummy.yml
  infra/k8s/kops-weave/flannel.yml
  infra/k8s/kops-weave/genie-plugin.yaml
  infra/k8s/kops-weave/weave-metrics-service.yml
  infra/k8s/kops-weave/weave-service-monitor.yml
  infra/k8s/kops-weave/weave.yml
  infra/k8s/limit-range/limit-range.yaml
  infra/k8s/prom-operator.yml
  infra/k8s/sidecar.yaml
  infra/k8s/testground-infra/Chart.yaml
  infra/k8s/testground-infra/charts/testground-dashboards/Chart.yaml
  infra/k8s/testground-infra/charts/testground-dashboards/dashboards
  infra/k8s/testground-infra/charts/testground-dashboards/templates/dashboard.yaml
  infra/k8s/testground-infra/charts/testground-dashboards/templates/datasource.yaml
  infra/k8s/testground-infra/requirements.lock
  infra/k8s/testground-infra/requirements.yaml
  infra/k8s/testground-infra/values.yaml
  infra/k8s/tools/README.md
  infra/k8s/tools/confirm_dns_route.sh
  infra/k8s/upgrade-testground-infra.sh
Labels: P1, area/docs

#858 sdk: unify sync and runtime into a single module.
  Dockerfile
  go.mod
  go.sum
  pkg/build/golang/docker.go
  pkg/build/golang/exec.go
  plans/benchmarks/go.mod
  plans/bitswap-tuning/go.mod
  plans/dht/go.mod
  plans/example/go.mod
  plans/network/go.mod
  plans/network/main.go
  sdk/README.md
  sdk/go.mod
  sdk/go.sum
  sdk/runtime/go.mod
  sdk/runtime/runenv.go
  sdk/sync/go.mod
  sdk/sync/go.sum
Labels: Status/Approved-Waiting

#872 change ipfs/testground to iptestground/sidecar
  .travis.yml
  Makefile
  pkg/runner/local_docker.go
Labels: Status/Approved-Waiting

#847 add pod ip to testplan env vars
  pkg/runner/cluster_k8s.go
Labels: status/waiting for review

#860 add pinger
  plans/verify/go.mod
  plans/verify/main.go
  plans/verify/manifest.toml
  sdk/go.mod
Labels: Status/Changes Requested

#867 Blackhole the control network
  pkg/sidecar/k8s_reactor.go
Labels: Status/Changes Requested

#895 migrate more project-specific plans out of this repo
  README.md
  compositions/barrier.toml
  compositions/uniq-artifacts.toml
  plans/bitswap-tuning/.gitignore
  plans/bitswap-tuning/Dockerfile
  plans/bitswap-tuning/README.md
  plans/bitswap-tuning/go.mod
  plans/bitswap-tuning/go.sum
  plans/bitswap-tuning/main.go
  plans/bitswap-tuning/manifest.toml
  plans/bitswap-tuning/suites/common.js
  plans/bitswap-tuning/suites/peer-selection/aggregate.js
  plans/bitswap-tuning/suites/peer-selection/chart.js
  plans/bitswap-tuning/suites/peer-selection/run.sh
  plans/bitswap-tuning/suites/perf/aggregate.js
  plans/bitswap-tuning/suites/perf/chart.js
  plans/bitswap-tuning/suites/perf/run.sh
  plans/bitswap-tuning/suites/version-compat/aggregate.js
  plans/bitswap-tuning/suites/version-compat/chart.js
  plans/bitswap-tuning/suites/version-compat/defs/one-leech-two-seeds.js
  plans/bitswap-tuning/suites/version-compat/gentomls.js
  plans/bitswap-tuning/suites/version-compat/run.sh
  plans/bitswap-tuning/test/fuzz.go
  plans/bitswap-tuning/test/transfer.go
  plans/bitswap-tuning/utils/createnode.go
  plans/bitswap-tuning/utils/files.go
  plans/bitswap-tuning/utils/metrics.go
  plans/bitswap-tuning/utils/net.go
  plans/bitswap-tuning/utils/params.go
  plans/bitswap-tuning/utils/peers.go
  plans/bitswap-tuning/utils/walker.go
  plans/chew-datasets/go.sum
  plans/message-delivery/README.md
  plans/naming/README.md
  plans/nodes-connectivity/README.md
Labels: Status/Approved-Waiting

#896 dockerfile for daemon service, with Go installed
  Dockerfile.daemon
  Dockerfile.sidecar
  Makefile
Labels: status/waiting for review

#899 Update Yaml labels
  .github/labels.yml
Labels: status/waiting for review

#915 improve CircleCI config; clean up go.mod/go.sum; .dockerignore more files
  .circleci/config.yml
  .dockerignore
  Dockerfile.testground
  Makefile
  go.mod
  go.sum
Labels: kind/improvement

#914 set pod memory and cpu based on group definition
  pkg/runner/cluster_k8s.go
Labels: kind/bug, status/waiting for review

#902 set build container network to `host` (needed for cluster:k8s runner)
  pkg/build/golang/docker.go
Labels: P1, Status/Approved-Waiting, area/infra, hint/needs-decision, hint/needs-team-input, kind/question

#913 generalise redis route to services routes; prepare for InfluxDB addition
  pkg/sidecar/docker_reactor.go
  pkg/sidecar/k8s_network.go
  pkg/sidecar/k8s_reactor.go
  pkg/sidecar/sidecar_linux.go
Labels: Status/Approved-Waiting, kind/improvement

#920 do not call wait-for-network-init
  pkg/runner/cluster_k8s.go
Labels: status/waiting for review

#924 add timeouts on n.cninet.AddNetworkList
  pkg/docker/manager.go
  pkg/sidecar/docker_reactor.go
  pkg/sidecar/k8s_network.go
Labels: status/waiting for review

#927 Add influxdb 1.8 to local healthchecks
  pkg/runner/local_common.go
Labels: area/runners, effort/minutes

#934 inject influxdb env variables; fix sidecar; fix image.
  pkg/config/loader.go
  pkg/runner/local_common.go
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
  pkg/sidecar/docker_reactor.go
Labels: area/observability, kind/feature

#936 adapt benchmarks plan to new SDK API.
  plans/benchmarks/benchmarks.go
  plans/benchmarks/go.mod
  plans/benchmarks/go.sum
Labels: kind/enhancement, status/waiting for review

#946 add influxdb host
  pkg/runner/cluster_k8s.go
Labels: status/waiting for review

#945 truncate latencies
  pkg/build/golang/docker.go
  pkg/runner/cluster_k8s.go
Labels: kind/hardening, status/waiting for review

#938 client-side plan management (attempt 3)
  README.md
  go.mod
  go.sum
  main.go
  pkg/cmd/build.go
  pkg/cmd/collect.go
  pkg/cmd/common.go
  pkg/cmd/daemon.go
  pkg/cmd/describe.go
  pkg/cmd/enum_flag.go
  pkg/cmd/healthcheck.go
  pkg/cmd/itest/build_test.go
  pkg/cmd/itest/common_test.go
  pkg/cmd/itest/describe_test.go
  pkg/cmd/itest/list_test.go
  pkg/cmd/itest/run_test.go
  pkg/cmd/itest/sidecar_test.go
  pkg/cmd/list.go
  pkg/cmd/plan.go
  pkg/cmd/root.go
  pkg/cmd/run.go
  pkg/cmd/sidecar.go
  pkg/cmd/terminate.go
Labels: Status/Changes Requested
