Repository testground/testground, pull requests merged in 2020-03, with the labels that each got.

#596 Switch S3 store for EFS
  cmd/collect.go
  cmd/run.go
  go.mod
  go.sum
  infra/k8s/README.md
  infra/k8s/delete.sh
  infra/k8s/efs-terraform/.gitignore
  infra/k8s/efs-terraform/backend.tf
  infra/k8s/efs-terraform/main.tf
  infra/k8s/efs-terraform/outputs.tf
  infra/k8s/efs-terraform/variables.tf
  infra/k8s/efs/manifest.yaml.spec
  infra/k8s/efs/rbac.yaml
  infra/k8s/install.sh
  infra/k8s/redis-values.yaml
  pkg/runner/cluster_k8s.go
Labels: area/infra, kind/improvement

#677 automatically expose pprof+prometheus endpoint.
  .dockerignore
  manifests/placebo.toml
  pkg/build/golang/Dockerfile.template
  pkg/docker/container.go
  pkg/runner/local_docker.go
  pkg/sidecar/docker_reactor.go
  pkg/tgwriter/tgwriter.go
  plans/placebo/main.go
  sdk/runtime/metrics.go
  sdk/runtime/runner.go
Labels: status/waiting

#702 local:docker runner: rate limit starting and deleting containers.
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
  pkg/runner/pretty.go
Labels: status/waiting

#712 harden redis and sync service.
  Dockerfile
  go.mod
  go.sum
  pkg/runner/local_docker.go
  sdk/sync/common.go
  sdk/sync/go.mod
  sdk/sync/go.sum
  sdk/sync/redis_bench_test.go
  sdk/sync/redis_test.go
Labels: status/waiting

#699 Explicit AWS region in install script
  infra/k8s/install.sh
Labels: status/waiting

#710 add build and push step timers
  pkg/build/golang/docker.go
Labels: P2, kind/improvement, status/waiting

#700 Remove unnecessary shell
  infra/k8s/README.md
  pkg/runner/cluster_k8s.go
Labels: P1, kind/bug, status/waiting

#707 consistent path for testground outputs
  pkg/runner/cluster_k8s.go
Labels: kind/bug, status/waiting

#721 shadow group var
  pkg/runner/cluster_k8s.go
Labels: P1, kind/bug

#718 remove initRunner. add initPool
  48d7fa97a0ee.tgz
  pkg/runner/cluster_k8s.go
Labels: status/waiting

#724 k8s: remove s3 bucket pod
  infra/k8s/install.sh
Labels: kind/bug, status/waiting

#725 disable transparent huge pages support in kernel
  infra/k8s/kops-weave/dummy.yml
Labels: kind/enhancement, status/waiting

#726 add net.netfilter.nf_conntrack_max
  infra/k8s/cluster.yaml
  infra/k8s/redis-values.yaml
Labels: kind/enhancement, status/waiting

#703 local exec healthchecks
  docs/USAGE.md
  pkg/runner/local_exec.go
Labels: status/waiting

#731 disable TestSidecar
  cmd/itest/sidecar_test.go
Labels: status/waiting

#730 local docker redis exporter
  dashboards/main.go
  infra/docker/testground-prometheus/prometheus.yml
  infra/docker/testground-redis-exporter/Dockerfile
  pkg/runner/local_docker.go
Labels: status/in-progress

#736 increase port-forward timeout in kubelet
  infra/k8s/cluster.yaml
Labels: kind/enhancement

#737 move testground services to control network
  infra/k8s/install.sh
  infra/k8s/testground-infra/values.yaml
Labels: kind/bug

#740 [bug]restore redis values
  infra/k8s/README.md
  infra/k8s/testground-infra/values.yaml
Labels: area/infra, dif/trivial, kind/bug, status/waiting

#742 engine: deduplicate group builds; perform only unique builds.
  compositions/uniq-artifacts.toml
  pkg/api/composition.go
  pkg/engine/engine.go
  plans/example/sync.go
Labels: status/waiting

#744 send delete after interval
  infra/k8s/install.sh
  sdk/runtime/runner.go
Labels: area/sdk-runtime

#754 bump up resource requests for pushgateway
  infra/k8s/testground-infra/values.yaml
Labels: status/waiting

#753 do not query logs if many testplan instances
  pkg/runner/cluster_k8s.go
Labels: status/waiting
