Repository testground/testground, pull requests merged in 2020-05, with the labels that each got.

#947 remove kops healthcheck
  pkg/runner/cluster_k8s.go
Labels: P1, kind/bug, status/waiting for review

#948 no cpu limits for collect-outputs pod
  pkg/runner/cluster_k8s.go
Labels: status/waiting for review

#950 fix healthcheck feedback to user
  pkg/engine/engine.go
Labels: P2, kind/improvement, status/waiting for review

#958 remove aws credentials from sample .env.toml
  env-example.toml
Labels: area/ux-cli, kind/improvement, status/waiting for review

#956 fix redis rdb snapshot complaints.
  pkg/runner/local_common.go
Labels: Status/Approved-Waiting, kind/bug

#964 clean up the CLI.
  README.md
  main.go
  pkg/cmd/build.go
  pkg/cmd/collect.go
  pkg/cmd/daemon.go
  pkg/cmd/describe.go
  pkg/cmd/enum_flag.go
  pkg/cmd/healthcheck.go
  pkg/cmd/plan.go
  pkg/cmd/root.go
  pkg/cmd/run.go
  pkg/cmd/sidecar.go
  pkg/cmd/terminate.go
Labels: kind/improvement, status/approved-waiting

#965 require flags on single run
  pkg/cmd/build.go
  pkg/cmd/run.go
Labels: area/ux-cli, dif/easy, status/approved-waiting

#961 Put getting started above "how does it work"
  README.md
Labels: P0, area/docs, hint/needs-team-input, kind/discussion

#970 fix a panic when processing compositions.
  pkg/api/composition.go
Labels: P0, kind/bug

#969 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area/docs, status/approved-waiting

#972 Update README.md
  README.md
Labels: area/docs, status/approved-waiting

#971 add toml annotation to selectors
  pkg/api/composition.go
Labels: area/builders, status/awaiting-review

#979 example/sync: tidy up; remove superfluous pubsub.
  plans/example/sync.go
Labels: kind/improvement, status/approved-waiting

#978 plan create cmd: output location of new test plan.
  pkg/cmd/plan.go
Labels: area/test-plan, status/approved-waiting

#984 docker:go builder: support Dockerfile extensions and CGO.
  pkg/build/golang/docker.go
  pkg/build/golang/exec.go
  plans/dockercustomize/go.mod
  plans/dockercustomize/go.sum
  plans/dockercustomize/main.go
  plans/dockercustomize/manifest.toml
Labels: area/builders, status/approved-waiting

#990 extract `default` network name
  pkg/sidecar/k8s_network.go
  pkg/sidecar/sidecar_linux.go
Labels: area/docs, kind/improvement

#1007 improve consistency and logging
  pkg/daemon/build.go
  pkg/daemon/healthcheck.go
  pkg/daemon/outputs.go
  pkg/daemon/run.go
  pkg/daemon/terminate.go
  pkg/engine/engine.go
  pkg/runner/local_docker.go
Labels: kind/improvement, status/awaiting-review

#988 docker generic builder
  .circleci/config.yml
  pkg/build/docker_generic.go
  pkg/build/docker_go.go
  pkg/build/registry.go
  pkg/cmd/itest/run_test.go
  pkg/engine/engine.go
  pkg/runner/cluster_k8s.go
  pkg/runner/local_docker.go
  plans/example/Dockerfile
  plans/example/artifact.go
  plans/example/artifact.txt
  plans/example/main.go
  plans/example/manifest.toml
Labels: area/builders, kind/enhancement, kind/feature, status/approved-waiting

#1019 fix .env.toml example
  env-example.toml
Labels: kind/bug

#1020 docker image: pull if not present
  pkg/runner/cluster_k8s.go
Labels: area/test-plan, impact/dx, kind/discussion, kind/enhancement, status/approved-waiting

#1015 `rpc` package tests
  pkg/rpc/rpc_test.go
  pkg/rpc/rpctest/rpctest.go
Labels: area/testing, status/approved-waiting

#1017 fix make test
  .circleci/config.yml
  Makefile
Labels: kind/bug, status/awaiting-review

#1024 deterministic docker image name and tag
  pkg/build/docker_generic.go
  pkg/build/docker_go.go
  pkg/build/registry.go
  pkg/docker/image.go
Labels: impact/dx, kind/enhancement, status/awaiting-review

#1009 `docker` package tests
  pkg/docker/docker_test.go
  pkg/docker/image.go
Labels: area/testing, kind/discussion, status/changes-requested

#1027 sidecar use Linkshape FilterAction
  go.mod
  go.sum
  pkg/runner/pretty.go
  pkg/sidecar/docker_network.go
  pkg/sidecar/instance.go
  pkg/sidecar/k8s_network.go
  pkg/sidecar/link.go
  pkg/sidecar/sidecar_linux.go
  plans/example/manifest.toml
  plans/splitbrain/go.mod
  plans/splitbrain/go.sum
  plans/splitbrain/main.go
  plans/splitbrain/manifest.toml
Labels: kind/improvement, status/approved-waiting

#1032 move docker images push to cluster:k8s runner
  env-example.toml
  pkg/api/runner.go
  pkg/build/docker_generic.go
  pkg/build/docker_go.go
  pkg/build/registry.go
  pkg/engine/engine.go
  pkg/runner/cluster_k8s.go
  pkg/runner/common.go
  pkg/runner/registry.go
Labels: status/awaiting-review

#1036 append sidecar logs to testground output
  pkg/runner/local_docker.go
  pkg/runner/pretty.go
Labels: status/approved-waiting

#1031 integration tests for sidecar on local:docker
  Makefile
  integration_tests/06_docker_network_ping-pong.sh
Labels: area/testing, status/awaiting-review

#1029 cluster:k8s, local:docker, local:exec integration tests - collect outputs
  .circleci/config.yml
  Makefile
  integration_tests/01_k8s_kind_placebo_ok.sh
  integration_tests/02_k8s_kind_placebo_stall.sh
  integration_tests/03_exec_go_placebo_ok.sh
  integration_tests/04_docker_placebo_ok.sh
  integration_tests/05_docker_placebo_stall.sh
  integration_tests/06_docker_network_ping-pong.sh
  integration_tests/header.sh
  pkg/cmd/plan.go
  pkg/runner/cluster_k8s.go
Labels: area/testing, status/approved-waiting

#1042 terminate go-proxy when testground terminate
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
Labels: P1, kind/bug, status/approved-waiting

#1037 resolve services on each test run
  go.mod
  go.sum
  pkg/runner/local_docker.go
  pkg/runner/local_exec.go
  pkg/sidecar/docker_reactor.go
  pkg/sidecar/k8s_reactor.go
Labels: P1, kind/bug, status/approved-waiting

#1045 add version command
  Dockerfile.sidecar
  Dockerfile.testground
  Makefile
  main.go
  pkg/cmd/root.go
  pkg/cmd/version.go
  pkg/version/version.go
Labels: P2, kind/enhancement, status/approved-waiting

#939 add unit tests to sidecar
  go.mod
  go.sum
  pkg/sidecar/docker_reactor.go
  pkg/sidecar/instance.go
  pkg/sidecar/mock.go
  pkg/sidecar/sidecar_linux.go
  pkg/sidecar/sidecar_test.go
Labels: P2, kind/problem, status/approved-waiting
